
services:

  dns.tiernogalvan.es:
    container_name: dns.tiernogalvan.es
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - dns.tiernogalvan.es:/opt/snitchdns/data
    ports:
      - 80:8888
    environment:
      DB_HOST: db
      DB_USER: app_user
      DB_PASS: app_db_password
      DB_NAME: app_db

volumes:
  dns.tiernogalvan.es:
